### PR TITLE
Problem: styx ./preview.sh isn't the live preview

### PR DESCRIPTION
**Pull request by clacke**
Solution: Update ./preview.sh to use `styx live` instead of
`styx preview`.

### CODE REVIEW

**Comment by clacke** [comment]
Wow. Don't run this when you're on battery. `styx live` eats 40% of 4 cores for me on macOS.

**Comment by sjmackenzie** [comment]
What a hog! @ericsagnes ( :-P )

**Comment by clacke** [comment]
I will look at this at some point and replace it with some supervisor for `styx preview` and `entr` to monitor the source files and poke the supervisor.

**Comment by sjmackenzie** [comment]
Ah probably not needed, maybe better to focus on hyperflow.

**Pull request merged**
