### PR TITLE
Problem: new-site: no roadmap page 

### PR DESCRIPTION
**Pull request by clacke**
Solution: Render roadmap from fractalide/fractalide CHANGELOG.json.

### CODE REVIEW

**Comment by clacke** [comment]
The way the template is written is a bit wonky in places. But it works!

It renders like hugo roadmap, apart from the differences between `CHANGELOG.json` and `data/roadmap/*.yml` and the usual whitespace and comments differences.

**Comment by sjmackenzie** [comment]
roadmap-screenshot

Note entirely sure about that :-)

**Comment by clacke** [comment]
I meant strictly on the source level. :-)

As far as I can tell the HTML is functionally equivalent to the hugo site, so maybe I'm missing some css or javascript somewhere.

**Comment by sjmackenzie** [comment]
@miguelsimoni do you know why the roadmap has gone all wonky? This is the nix implementation.

**Comment by sjmackenzie** [comment]
There seems to be a large diff between 
https://github.com/fractalide/fractalide-website-styx/blob/master/fractalide-hugo-theme/static/css/custom.css
and 
https://github.com/fractalide/fractalide-website-styx/blob/master/new-site/themes/fractalide/files/css/custom.css

**Comment by sjmackenzie** [comment]
Okay that did it, it seems like you're using the wrong CSS document. maybe @miguelsimoni can confirm that https://github.com/fractalide/fractalide-website-styx/blob/master/fractalide-hugo-theme/static/css/custom.css is the correct one (because that one rendered correctly! :-) )

**Comment by sjmackenzie** [comment]
Well it's the nix version isn't the same as the hugo version because the progress bars are much smaller.

**Comment by clacke** [comment]
If new-site static files differ from hugo static files, just nuke them. I haven't modified them anything, so nothing would be lost. If they differ, they're simply behind.

**Pull request merged**
