### PR TITLE
Problem: few typos in cardano-wallet & need of elaboration

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: change download button from "Download Center" to
"Download Cantor" and elaborate on features

### CODE REVIEW

**Comment by clacke** [comment]
Should it say "coming soon" on all of them? I think the current page gives the idea that c-w[0] for Linux 1.0.0 exists.

[0] Oh, nice initials!

**Comment by sjmackenzie** [comment]
Well there is nothing there to download. So ... it's coming soon... you're welcome to make a PR and improve it

**Comment by sjmackenzie** [comment]
But it does say "Coming soon" on all of them.

**Comment by clacke** [comment]
Oh! You had `Coming soon` everywhere in *this* PR already.

D'oh.

**Pull request merged**
