### PR TITLE
Hyperflow & Fractalmarket

### PR DESCRIPTION
**Pull request by sjmackenzie**

### CODE REVIEW

**Comment by clacke** [comment]
We're not speaking American?

**Comment by sjmackenzie** [comment]
Draw and quarter me if we do! :-)

**Comment by clacke** [comment]
Scottish South African English it is. ;-)

**Comment by sjmackenzie** [comment]
Ay, lekker my china!

**Comment by clacke** [comment]
Fractalide issue: Problem: No en_ZA glossary in documentation

**Pull request merged**
